// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbybGQtiJpsNoiA1EMN53zVVTTxrx0K4Y',
    appId: '1:1086981033213:web:f8bc2daef8aa26f6fa8294',
    messagingSenderId: '1086981033213',
    projectId: 'learnspacefirebase',
    authDomain: 'learnspacefirebase.firebaseapp.com',
    storageBucket: 'learnspacefirebase.appspot.com',
    measurementId: 'G-P2CB8PJRQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2Z5_887O4BvkfHtRT6C2Ne-y0bmTcpY',
    appId: '1:1086981033213:android:2908455e99db22f1fa8294',
    messagingSenderId: '1086981033213',
    projectId: 'learnspacefirebase',
    storageBucket: 'learnspacefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeE7JyZ5XRFdHF7QBe5jdP_t-EQOp9ktg',
    appId: '1:1086981033213:ios:850549c3ab8c95b7fa8294',
    messagingSenderId: '1086981033213',
    projectId: 'learnspacefirebase',
    storageBucket: 'learnspacefirebase.appspot.com',
    iosClientId: '1086981033213-4u5n27j1vq7q2qu1g2iigoiqa8du9fpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeE7JyZ5XRFdHF7QBe5jdP_t-EQOp9ktg',
    appId: '1:1086981033213:ios:850549c3ab8c95b7fa8294',
    messagingSenderId: '1086981033213',
    projectId: 'learnspacefirebase',
    storageBucket: 'learnspacefirebase.appspot.com',
    iosClientId: '1086981033213-4u5n27j1vq7q2qu1g2iigoiqa8du9fpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbybGQtiJpsNoiA1EMN53zVVTTxrx0K4Y',
    appId: '1:1086981033213:web:da78f95b84c8e7edfa8294',
    messagingSenderId: '1086981033213',
    projectId: 'learnspacefirebase',
    authDomain: 'learnspacefirebase.firebaseapp.com',
    storageBucket: 'learnspacefirebase.appspot.com',
    measurementId: 'G-QDT87NG801',
  );

}